name: mainsite
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.7.*
  - jupyter
  - sphinx=2.4.4
  - pip
  - nbconvert
  - pip:
    - git+https://github.com/executablebooks/jupyter-book
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
   
    
