name: mainsite
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.7.*
  - jupyter
  - runjb
  - sphinx=2.4.4
  - pydata-sphinx-theme
  - ghp-import
  - pip
  - pip:
    - sphinx_rtd_theme
    - git+https://github.com/executablebooks/MyST-NB.git
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
   
    
