name: mainsite
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.8
  - pip
  - jupyter-book
  - ghp-import
  - conda-lock
  - mamba
# conda-lock --file environment.yml -p linux-64
