#######################################################################################
# For settings see https://jupyterbook.org/customize/config.html
#######################################################################################

# Book settings
title : OCESE Documentation
author: everyone
logo: images/logo-04smsm.png
copyright: "2023"  # Copyright year to be placed in the footer

# Information about where the book exists on the web
description: >-
  draft book

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface          : "notebook"
